name: CI Pipeline

on:
  pull_request:
    branches:
    - main
  push:
    tags:
      - '*'
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      LD_LIBRARY_PATH: /home/runner/.mujoco/mujoco210/bin

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install MuJoCo
      run: |
        sudo apt-get install libosmesa6-dev
        cd /tmp
        wget https://github.com/deepmind/mujoco/releases/download/2.1.0/mujoco210-linux-x86_64.tar.gz
        tar -xf mujoco210*.tar.gz
        mkdir $HOME/.mujoco
        mv mujoco210 $HOME/.mujoco

    - name: Install tox
      run: pip install --upgrade tox

    - name: Run tests
      run: tox -e py39-test

    - uses: codecov/codecov-action@v3
      with:
        files: reports/coverage.xml

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install tox
      run: pip install --upgrade tox

    - name: Run static checks
      run: tox -e py39-lint

  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install MuJoCo
      run: |
        sudo apt-get install libosmesa6-dev
        cd /tmp
        wget https://github.com/deepmind/mujoco/releases/download/2.1.0/mujoco210-linux-x86_64.tar.gz
        tar -xf mujoco210*.tar.gz
        mkdir $HOME/.mujoco
        mv mujoco210 $HOME/.mujoco

    - name: Install tox
      run: pip install --upgrade tox

    - name: Build docs
      run: tox -e docs

  publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: [lint, test, docs]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install build
      run: pip install build

    - name: Publish to PyPi
      uses: pypa/gh-action-pypi-publish@v1.5.1
      with:
        skip_existing: true
        user: __token__
        password: ${{ secrets.pypi_token }}
