name: Run static checks and tests and build the docs

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install tox
      run: pip install --upgrade tox

    - name: Run tests
      run: tox -e py39-test

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install tox
      run: pip install --upgrade tox

    - name: Run static checks
      run: tox -e py39-lint

  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install tox
      run: pip install --upgrade tox

    - name: Build docs
      run: tox -e docs
