name: CI Pipeline

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      LD_LIBRARY_PATH: $HOME/.mujoco/mujoco210/bin

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install MuJoCo
      run: |
        cd /tmp
        wget https://github.com/deepmind/mujoco/releases/download/2.1.0/mujoco210-linux-x86_64.tar.gz
        tar -xf mujoco210*.tar.gz
        mkdir $HOME/.mujoco
        mv mujoco210 $HOME/.mujoco

    - name: Install tox
      run: pip install --upgrade tox

    - name: Run tests
      run: tox -e py39-test

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install tox
      run: pip install --upgrade tox

    - name: Run static checks
      run: tox -e py39-lint

  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install tox
      run: pip install --upgrade tox

    - name: Build docs
      run: tox -e docs
